kubeconfig_details:
  path: "/root/.kube/config"
  ip_address: "10.xxx.xx.xx"
  username: "root"
  password: "xxxxxxxx"
destination_path: "/home"
#driver_path:
#  csi-unity: "/root/csi-unity"
#  csi-powerstore: "/root/csi-powerstore"
#  csi-powerscale: "/root/csi-powerscale"
#  csi-powermax: "/root/csi-powermax"
#  csi-powerflex: "/root/csi-powerflex"
