name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["type/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create a CSM log collector bug report. To better help us investigate this bug, please provide the information below.
  - type: input
    id: application-version
    attributes:
      label: CSM log collector appliction version
      description: Which version of CSM log collector application is being used?
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    id: application-installation
    attributes:
      label: CSM log collector appliction installation
      description: How was the CSM log collector application installed? Using docker image or cloning GIT repository.
    validations:
      required: true
  - type: input
    id: docker-image
    attributes:
      label: Docker image version of CSM log collector application
      description: Please specify the docker image and its version used for deploying the application.
      placeholder: Docker image version
    validations:
      required: false
  - type: textarea
    id: application-config-file
    attributes:
      label: Application configuration file details
      description: What values were provided in the application configuration file, config.yml. Please make sure to remove all sensitive data such as IP addresses, host names, credentials, etc.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Logs
      description: Copy/paste the <timestamp>_log.txt file available on root folder of binary (root/csm-logcollector) here or Upload it by dragging and dropping the file into the text area. Please make sure to remove all sensitive data such as IP addresses, host names, credentials, etc.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload any relevant screenshots here by dragging and dropping the files into the text area.
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: Additional Environment Information
      description: Provide additional environment information such as operating environment, how the CSI drivers were delpoyed, driver version, driver details, namespace etc.
    validations:
      required: false  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can be taken to reproduce the bug?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: driver
    attributes:
      label: CSI Driver(s)
      description: Please list the CSI drivers and versions for what the log was targeted for collection.
      placeholder: |
        CSI Driver for PowerFlex v2.1
        CSI Driver for PowerScale v2.1
        CSI Driver for PowerMax v2.1
        CSI Driver for PowerStore v2.1
        CSI Driver for Unity XT v2.1
    validations:
      required: true
  - type: input
    id: install
    attributes:
      label: Installation Type
      description: What installation type was used? Operator or Helm? Please provide the version as well.
      placeholder: Operator v1.6.1
    validations:
      required: false
  - type: input
    id: co
    attributes:
      label: Container Orchestrator
      description: Which container orchestrator is being used? Please provide the version as well.
      placeholder: Kubernetes 1.23.1
    validations:
      required: true  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system is being used? Please provide the version as well.
      placeholder: RHEL 7.6
    validations:
      required: true