# This config.yml is consumed for unit testing.
#Hence, This config file contains only dummy values.
kubeconfig_details:
  path: "/root/.kube/config"
  ip_address: "xxx.xxx.xxx.xxx"
  username: "sample_user"
  password: "sample_password"
destination_path: "/root/"
secrets:
  use_secrets: "true"
driver_path:
  csi-unity: "/root/csi-unity"
  csi-powerstore: "/root/csi-powerstore"
  csi-powerscale: "/root/csi-powerscale"
  csi-powermax: "/root/csi-powermax"
  csi-powerflex: "/root/csi-powerflex"
